services:
  - type: web
    name: financial-statement-analyzer
    env: node
    runtime: node
    buildCommand: npm install --production && npm rebuild sqlite3
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.18.0 